# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-policy-propagator-metrics
  labels:
    app: {{ template "grc.name" . }}
    chart: {{ template "grc.chart" . }}
    component: "ocm-policy-propagator"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "grc.name" . }}
    helm.sh/chart: {{ template "grc.chart" . }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Release.Name }}-grc-metrics-cert
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: {{ template "grc.name" . }}
    component: "ocm-policy-propagator"
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
